version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.5
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./01-mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always
